### ISSUE TITLE
Support: RHOAI v6 migration

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/pf-roadmap#183]
take @jeff-phillips-18 [WIP PR](https://github.com/opendatahub-io/odh-dashboard/pull/3038) and run with it. Any questions on where to look for overrides, Jeff can help point people in the right directions.

PRs could be opened again the WIP PR, or commits can be made directly into the PR, depending on level of comfort.

Once we've made significant progress on these updates, we will engage with UXD designers (likely Jenn Giardino and Simran Dhaliwal) to do a design review of the PR, to check that nothing is broken or poorly formatted following the migration.

**Comment by thatblindgeye** [comment]
In AboutDialog, the styling of the Alert title looks off. Because it's rendered inside a Content component, there's margin-block-start styling being applied to the `h4.pf-v6-c-alert__title` element which pushes it down compared to the icon:
  ![image](https://github.com/user-attachments/assets/4846f187-f53d-45ff-94eb-7412bb583d29)

**Comment by thatblindgeye** [comment]
The custom Switch styling in `frontend/src/app/App.scss` needs to be updated, it's causing the Switch toggle to be misaligned due to the sizing update:

![image](https://github.com/user-attachments/assets/e09080b4-8a95-4863-8c2d-f733484d2e04)

**Comment by andrew-ronaldson** [comment]
What is the status of this issue? Should we break this into a task list?

**Comment by thatblindgeye** [comment]
@andrew-ronaldson the initial updates had been made, as well as a few followup updates as Jeff has rebased his draft PR. Currently the state of things are:

- product designers are finishing up with a UI review and any issues found will be reviewed and finalized for any recommendations at the end of their current sprint
- as Jeff rebases his draft PR I'll continue checking if there's anything else needing update - FWIW the last couple of updates have been much smaller than the initial (2-5 files with very straight forward updates)
- Jeff and I will basically be going through any issues found from the UI review and make updates as necessary. There's a [jira epic tracking the UI review](https://issues.redhat.com/browse/RHOAIUX-434), and each child issue of that epic should have a Google doc linked within it that outlines issues the designers may have found
- any major bugs found in the UI review designers will reach out to Jeff and/or I on Slack for more immediate attention - thus far from what I've seen this hasn't happened too much so far
